### PR TITLE
Create manifest V3 version of the extension

### PR DESCRIPTION
**Pull request by tom-james-watson**
Closes https://github.com/tom-james-watson/old-reddit-redirect/issues/114

This adds support to manifest v3, which is a migration that is required for this extension to not be removed from the chrome web store.

I'm doing a small rollout of this new version 2.0.0 to check for any bugs. If that goes smoothly then I will fully roll out to all users.

### CODE REVIEW

**Comment by tom-james-watson** [comment]
@JodanJodan, @francium, @Samulus, @9ary, @Lachcim - pinging you because you made decent code contributions in the past to this extension. Hope you don't mind.

I could do with some more eyes on this new manifest v3 version of the extension. It would be greatly appreciated if you could check this branch out and test the manifest v3 version on Chrome. As far as I can tell, I managed to migrate all of the existing functionality. Let me know if you are able to have a look and if you see any issues. Thank you! 🙏

**Comment by Lachcim** [comment]
I gave it a go and it appears to work just fine. Thanks for maintaining this mission-critical extension ❤

**Comment by 9ary** [comment]
I'm afraid I can't help since I only use Firefox. Great work though, if it were me I would probably have abandoned Chrome support. :P

**Comment by tom-james-watson** [comment]
It crossed my mind, that's for sure...

In the end though I actually like the V3 implementation a lot. It's just a declarative set of static rules. I'd love to have only one version of the extension, but the V3 version doesn't seem to work on Firefox for some unknown reason. I'll check back in the future to see if that changes. For now Firefox will stay on the V2 version.

**Comment by haseebT** [comment]
Hi @tom-james-watson , I noticed the extension was auto disabled by Chrome this morning due to new permissions:

1. Read and change your data on old.reddit.com
2. Block content on any page.

Can you explain why these new permissions are needed? Is it due to V3?

**Comment by tom-james-watson** [comment]
The extension was rewritten to migrate from manifest v2 to v3. Chrome considers the way network requests can be redirected in V3 to be "blocking content". And I assume old.reddit.com is now listed because they now also list that domain due to being used in redirects or for content scripts (CSS).

**Comment by tom-james-watson** [comment]
Merging to reflect the fact that this was published to chrome web store. At the moment it's only pushed to 5% of users (in theory). Will push to the rest once I'm happy it's stable.

**Comment by francium** [comment]
I meant to help out, but didn't get the time to do so before you merged, sorry.

**Comment by tom-james-watson** [comment]
No worries. I didn't exactly give you long! It's still definitely helpful to double check that it works though!

**Comment by francium** [comment]
Checked latest `main` on Chrome Windows 10 and Chromium Linux. Works fine after clicking around homepage, images, links, comments. I don't use reddit much anymore, so I won't be able to do any more advanced or thorough testing.

**Pull request merged**
