### PR TITLE
Fix infinite loop when open a RSS or JSON url

### PR DESCRIPTION
**Pull request by un-pogaz**
Fix infinite loop when open a RSS or JSON url

### CODE REVIEW

**Comment by tom-james-watson** [comment]
Do you have example URLs?

**Comment by tom-james-watson** [comment]
Just to confirm - with just this extension installed, there's no problem? You can close this out in that case :) Thanks!

**Comment by un-pogaz** [comment]
With just this extension installed, no problem.

**Comment by tom-james-watson** [comment]
Ok, will consider this not a bug then

**Comment by tom-james-watson** [comment]
The subdomain new.reddit.com doesn't exist anymore. It just always redirects to www.reddit.com. Nothing to do with the extension.

**Comment by john-bao-git** [comment]
The subdomain still does exist, pic included, if I type https://new.reddit.com/ in my url, unless I'm misunderstanding something.

image

**Comment by tom-james-watson** [comment]
Ah, it seems to be working again. It had started doing a redirect to www.reddit.com a few weeks back.

**Comment by john-bao-git** [comment]
Ah ok, you're right, if that's the case, then it wasn't the extension. Still, would it be possible to take out new.reddit from the whitelist now that it's back?

**Comment by tom-james-watson** [comment]
https://github.com/tom-james-watson/old-reddit-redirect/issues/122

**Pull request closed without merging**
