### PR TITLE
ignore /rpan (radio) urls

### PR DESCRIPTION
**Pull request by MaxLeiter**
It's only a five day test so not sure if this should be merged. Currently the url doesnt work on old.reddit.com

### CODE REVIEW

**Comment by ahartschen** [comment]
I don't think it will hurt even if it is only the test. It makes it harder for users of this extension to enjoy it.

**Comment by tom-james-watson** [comment]
Can you give me an example link? I'm not sure what this is referring to

**Comment by MaxLeiter** [comment]
www.reddit.com/rpan

**Comment by tom-james-watson** [comment]
That just loads a blank page that says "Not Found"

**Comment by MaxLeiter** [comment]
Not sure what to say. be sure you aren’t using old.reddit.com? more info here at /r/pan. it’s an official reddit project

**Comment by MaxLeiter** [comment]
oh, experiment is over. didn’t realize I was late to it. will close and re open if rpan is ever made permanent

**Comment by tom-james-watson** [comment]
Ah ok. Sounds good - thanks!

**Pull request closed without merging**
